name: Keep Versions Up-To-Date

on:
  release:
    types: [published, edited]

jobs:
  actions-tagger:
    runs-on: ubuntu-latest
    steps:
      - uses: Actions-R-Us/actions-tagger@95c51c646e75db5c6b7d447e3087bcee58677341
        env:
          GITHUB_TOKEN: '${{ github.token }}'
